[package]
name = "rendy-shader"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-shader"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's shader compilation tool"

[dependencies]
failure = "0.1"
gfx-hal = "0.1"
rendy-factory = { version = "0.1", path = "../factory" }
shaderc = { version = "0.3", optional = true }

[features]
shader-compiler = ["shaderc"]