[package]
name = "rendy-shader"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
gfx-hal = "0.1.0"
rendy-factory = { version = "0.1", path = "../factory" }
shaderc = "0.3"
