language: rust
compiler: clang
cache: cargo

env:
  global: RUSTFLAGS="-D warnings" RUST_LOG=info

rust: stable

matrix:
  include:
    # # Linux 64bit
    # - os: linux

    # # macOS 64bit
    # - env: MACOSX_DEPLOYMENT_TARGET=10.9
    #   os: osx
    #   osx_image: xcode10.2
    #   # We need travis_wait here to ensure the build doesn't timeout due to
    #   # shader compilation
    #   script: travis_wait 30 make

    # iPhoneOS 64bit
    - env: TARGET=aarch64-apple-ios
      os: osx
      osx_image: xcode10.2
      # We need travis_wait here to ensure the build doesn't timeout due to
      # shader compilation
      script: travis_wait 45 make

    # # Windows 64bit
    # - os: windows
    #   env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

branches:
  only:
    # Only build on master as sanity check
    - master
    # - staging
    # - trying

before_install:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install make; choco install ninja; fi
  - rustup self update
  - if [[ ! -z "$TARGET" ]]; then rustup target add $TARGET; fi

script:
  - make
