[workspace]

members = [
    "command",
    "descriptor",
    "factory",
    "frame",
    "init",
    "memory",
    "mesh",
    "rendy",
    "resource",
    "shader",
    "wsi",
    "chain",
    "graph",
    "core",
    "tests",
    "texture",
]
