[package]
name = "rendy-memory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
gfx-hal = { path = "../../gfx/src/hal" }
derivative = "1.0"
failure = "0.1"
log = "0.4"
hibitset = "0.5"
relevant = "0.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
veclist = "0.1"

[dev-dependencies]
rand = "0.5"
