[package]
name = "rendy-wsi"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[features]
empty = ["gfx-backend-empty"]
dx12 = ["gfx-backend-dx12"]
metal = ["gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
rendy-resource = { path = "../resource" }

gfx-hal = "0.1.0"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = "0.3"
smallvec = "0.6"
winit = "0.18"
