[package]
name = "rendy-factory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-factory"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's factory tool"

[features]
empty = ["gfx-backend-empty", "rendy-wsi/gfx-backend-empty", "rendy-util/empty"]
dx12 = ["gfx-backend-dx12", "rendy-wsi/gfx-backend-dx12", "rendy-util/dx12"]
metal = ["gfx-backend-metal", "rendy-wsi/gfx-backend-metal", "rendy-util/metal"]
vulkan = ["gfx-backend-vulkan", "rendy-wsi/gfx-backend-vulkan", "rendy-util/vulkan"]
serde-1 = [
    "serde",
    "rendy-memory/serde-1",
    "gfx-hal/serde",
]
no-slow-safety-checks = ["rendy-util/no-slow-safety-checks"]
interact-0 = ["interact", "rendy-memory/interact-0"]

[dependencies]
rendy-memory = { version = "0.1", path = "../memory" }
rendy-resource = { version = "0.1", path = "../resource" }
rendy-command = { version = "0.1", path = "../command" }
rendy-descriptor = { version = "0.1", path = "../descriptor" }
rendy-wsi = { version = "0.1", path = "../wsi" }
rendy-util = { version = "0.1", path = "../util" }

gfx-hal = "0.1"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

derivative = "1.0"
either = "1.0"
failure = "0.1"
log = "0.4"
parking_lot = "0.7"
relevant = { version = "0.4", features = ["log", "backtrace"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.18"
interact = { version = "0.3", optional = true }
interact_prompt = { version = "0.3", optional = true }
