[package]
name = "rendy-factory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[features]
empty = ["gfx-backend-empty", "rendy-wsi/gfx-backend-empty"]
dx12 = ["gfx-backend-dx12", "rendy-wsi/gfx-backend-dx12"]
metal = ["gfx-backend-metal", "rendy-wsi/gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan", "rendy-wsi/gfx-backend-vulkan"]

[dependencies]
derivative = "1.0"
failure = "0.1"
gfx-backend-empty = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-backend-dx12 = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-backend-metal = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx", optional = true }
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }
log = "0.4"
relevant = "0.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.18"

rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
rendy-command = { path = "../command" }
rendy-wsi = { path = "../wsi" }
