[package]
name = "rendy-graph"
version = "0.4.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-graph"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's render graph"

[features]
empty = ["rendy-util/gfx-backend-empty"]
dx12 = ["rendy-util/gfx-backend-dx12"]
metal = ["rendy-util/gfx-backend-metal"]
vulkan = ["rendy-util/gfx-backend-vulkan"]
no-slow-safety-checks = ["rendy-util/no-slow-safety-checks"]
profiler = ["thread_profiler/thread_profiler"]

[dependencies]
rendy-chain = { version = "0.4.0", path = "../chain" }
rendy-command = { version = "0.4.0", path = "../command" }
rendy-descriptor = { version = "0.4.0", path = "../descriptor" }
rendy-factory = { version = "0.4.0", path = "../factory" }
rendy-frame = { version = "0.4.0", path = "../frame" }
rendy-memory = { version = "0.4.0", path = "../memory" }
rendy-resource = { version = "0.4.0", path = "../resource" }
rendy-util = { version = "0.4.0", path = "../util" }
rendy-wsi = { version = "0.4.0", path = "../wsi" }
rendy-shader = { version = "0.4.0", path = "../shader" }

gfx-hal = "0.3"

either = "1.5"
bitflags = "1.0"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
thread_profiler = "0.3"
