[package]
name = "rendy-graph"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-graph"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's render graph"

[features]
empty = ["gfx-backend-empty", "rendy-wsi/gfx-backend-empty", "rendy-factory/gfx-backend-empty", "rendy-util/empty"]
dx12 = ["gfx-backend-dx12", "rendy-wsi/gfx-backend-dx12", "rendy-factory/gfx-backend-dx12", "rendy-util/dx12"]
metal = ["gfx-backend-metal", "rendy-wsi/gfx-backend-metal", "rendy-factory/gfx-backend-metal", "rendy-util/metal"]
vulkan = ["gfx-backend-vulkan", "rendy-wsi/gfx-backend-vulkan", "rendy-factory/gfx-backend-vulkan", "rendy-util/vulkan"]

[dependencies]
rendy-chain = { version = "0.1.0", path = "../chain" }
rendy-command = { version = "0.1.0", path = "../command" }
rendy-descriptor = { version = "0.1.0", path = "../descriptor" }
rendy-factory = { version = "0.1.0", path = "../factory" }
rendy-frame = { version = "0.1.0", path = "../frame" }
rendy-memory = { version = "0.1.0", path = "../memory" }
rendy-resource = { version = "0.1.0", path = "../resource" }
rendy-util = { version = "0.1.0", path = "../util" }
rendy-wsi = { version = "0.1.0", path = "../wsi" }
rendy-shader = { version = "0.1.0", path = "../shader" }

gfx-hal = "0.1"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

either = "1.5"
bitflags = "1.0"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.18"
