[package]
name = "rendy-graph"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[features]
empty = ["gfx-backend-empty", "rendy-wsi/gfx-backend-empty", "rendy-factory/gfx-backend-empty"]
dx12 = ["gfx-backend-dx12", "rendy-wsi/gfx-backend-dx12", "rendy-factory/gfx-backend-dx12"]
metal = ["gfx-backend-metal", "rendy-wsi/gfx-backend-metal", "rendy-factory/gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan", "rendy-wsi/gfx-backend-vulkan", "rendy-factory/gfx-backend-vulkan"]

[dependencies]
rendy-chain = { path = "../chain" }
rendy-command = { path = "../command" }
rendy-factory = { path = "../factory" }
rendy-frame = { path = "../frame" }
rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
rendy-wsi = { path = "../wsi" }

gfx-hal = "0.1.0"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

either = "1.5"
bitflags = "1.0"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.18"
