[package]
name = "rendy"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[features]
empty = ["rendy-factory/empty", "rendy-graph/empty", "rendy-wsi/empty", "gfx-backend-empty"]
dx12 = ["rendy-factory/dx12", "rendy-graph/dx12", "rendy-wsi/dx12", "gfx-backend-dx12"]
metal = ["rendy-factory/metal", "rendy-graph/metal", "rendy-wsi/metal", "gfx-backend-metal"]
vulkan = ["rendy-factory/vulkan", "rendy-graph/vulkan", "rendy-wsi/vulkan", "gfx-backend-vulkan"]
serde-1 = ["gfx-hal/serde", "rendy-factory/serde-1", "rendy-mesh/serde-1", "rendy-texture/serde-1"]

command = ["rendy-command"]
factory = ["rendy-factory", "command", "resource", "wsi"]
frame = ["rendy-frame", "factory"]
graph = ["rendy-graph", "frame"]
memory = ["rendy-memory"]
mesh = ["rendy-mesh", "factory", "util"]
shader = ["rendy-shader", "factory"]
resource = ["rendy-resource", "memory"]
texture = ["rendy-texture", "factory", "util"]
util = ["rendy-util"]
wsi = ["rendy-wsi"]

full = ["graph", "mesh", "texture", "shader"]
default = ["full"]

[dependencies]
rendy-command = { path = "../command", optional = true }
rendy-factory = { path = "../factory", optional = true }
rendy-frame = { path = "../frame", optional = true }
rendy-graph = { path = "../graph", optional = true }
rendy-memory = { path = "../memory", optional = true }
rendy-mesh = { path = "../mesh", optional = true }
rendy-shader = { path = "../shader", optional = true }
rendy-resource = { path = "../resource", optional = true }
rendy-texture = { path = "../texture", optional = true }
rendy-util = { path = "../util", optional = true }
rendy-wsi = { path = "../wsi", optional = true }

gfx-hal = "0.1.0"
gfx-backend-empty = { version = "0.1.0", optional = true }
gfx-backend-dx12 = { version = "0.1.0", optional = true }
gfx-backend-metal = { version = "0.1.0", optional = true }
gfx-backend-vulkan = { version = "0.1.0", optional = true }

[dev-dependencies]
env_logger = "0.5"
failure = "0.1"
lazy_static = "1.0"
image = "0.20.1"
log = "0.4"
winit = "0.18"
palette = "0.4"
rand = "0.6"
