[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-resource"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's resource manager"

[dependencies]
gfx-hal = "0.1"
crossbeam-channel = "0.2"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
rendy-descriptor = { version = "0.1.0", path = "../descriptor" }
rendy-memory = { version = "0.1.0", path = "../memory" }
smallvec = "0.6"
