[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
gfx-hal = "0.1.0"
crossbeam-channel = "0.2"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = "0.2"
rendy-memory = { path = "../memory" }
