[package]
name = "rendy-resource"
version = "0.4.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-resource"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's resource manager"

[features]
no-slow-safety-checks = ["rendy-util/no-slow-safety-checks"]

[dependencies]
gfx-hal = "0.3"
crossbeam-channel = "0.3"
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = { version = "0.4", features = ["log", "backtrace"] }
rendy-descriptor = { version = "0.4.0", path = "../descriptor" }
rendy-memory = { version = "0.4.0", path = "../memory" }
rendy-util = { version = "0.4.0", path = "../util" }
smallvec = "0.6"
