[package]
name = "rendy-chain"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/amethyst/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-chain"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's node synchronization tool"

[features]
profiler = ["thread_profiler/thread_profiler"]

[dependencies]
gfx-hal = "0.2"
rendy-util = { version = "0.1", path = "../util" }
fnv = "1.0"
log = "0.4"
thread_profiler = "0.3"
